[CLIENT-4869] Ensure that macOS fails to compile when encountering compiler warnings (#1153)
There was a compiler warning that turned into an error on macOS when building the Python client at b6be24a with CFLAGS=-Werror.

src/main/convert_expressions.c:356:25: error: initializer overrides prior initialization of this subobject [-Werror,-Winitializer-overrides]
  356 |         [OP_MAP_SIZE] = EXP_SZ(as_exp_map_size(NULL, NIL)),

This was fixed in the following commit 5c6294d, but we enable -Werror for all macOS builds to be sure that this mistake isn't repeated in the future.