Fix syntax error in truncate.c
Fix syntax error in truncate.c causing the below exception:

      src/main/client/truncate.c:133:5: error: expected '(' after 'if'
              if PyLong_Check(py_nanos) {
                 ^